# This Dockerfile is for local dev.
# Don't use this in production
FROM python:3.12-slim-bookworm

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

RUN useradd --create-home --user-group github
USER github
WORKDIR /code

# COPY ./pyproject.toml ./uv.lock* ./src ./bin /code/
COPY ./pyproject.toml /code/pyproject.toml
COPY ./uv.lock /code/uv.lock
COPY ./src /code/src
COPY ./bin /code/bin

# COPY ./pyproject.toml ./uv.lock* ./src ./bin /code/
# COPY ./pyproject.toml ./uv.lock* ./src ./bin /code/
# COPY ./pyproject.toml ./uv.lock* ./src ./bin /code/
# COPY ./pyproject.toml ./uv.lock* ./src ./bin /code/
# COPY ./pyproject.toml ./uv.lock* ./src ./bin /code/
# COPY ./pyproject.toml ./uv.lock* ./src ./bin /code/
# COPY ./pyproject.toml ./pyproject.toml
# COPY ./uv.lock ./uv.lock
RUN uv sync --frozen

RUN touch test.txt
# RUN uv sync
RUN ls -l .venv
RUN ls -l .venv/bin/activate
RUN ls -l /code/.venv/bin/activate
# ENV PATH="/home/github/.local/bin:${PATH}"

#COPY ./src /code/src
#COPY ./bin /code/bin

ENV PORT=8000

# For the benefit of thehub when run its dev server on http://localhost:3000
ENV CORS_ORIGINS=http://localhost:3000
# Disable all HMAC security in this context
ENV HMAC_SECRET=""

# Not sure if this is necessary
# ENV VIRTUAL_ENV=/code/.venv
# ENV PATH="/code/.venv/bin:$PATH"

EXPOSE $PORT

ENTRYPOINT [ "/bin/bash", "/code/bin/run.sh" ]

CMD ["web-dev"]
