import type { GetServerSideProps } from "next";
import Head from "next/head";
import styles from "@/styles/Home.module.css";

export default function Name({ name }: { name: string }) {
  return (
    <>
      <Head>
        <title>{name}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>{name}</h1>
      </main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async ({ params }) => {
  const name = params?.name || "No name";
  return {
    props: {
      name,
    },
  };
};
