name: GitHub Blog Feed to YAML

on:
  workflow_dispatch: # Manually trigger workflow (mostly for debugging)
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours
  pull_request:
    paths:
      - '.github/workflows/blog-feed-to-yaml.yml'

permissions:
  contents: write

# Only one instance of this workflow can run at a time since it can depend on the previous run's committed changes
concurrency:
  group: '${{ github.workflow }}'
  cancel-in-progress: false

jobs:
  blog-feed-to-yaml:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run script to post new articles to Chatterbox, which posts to Slack
        working-directory: .github/actions/js
        run: |
          curl https://github.blog/feed/ | grep title > blog-feed.txt

      - name: Inspect change
        run: |
          git status

      - name: Commit changes to branch
        if: ${{ github.event_name != 'pull_request' }}
        # env:
        #   GITHUB_TOKEN: ${{ secrets.THEHUB_BOT_PAT }}
        run: |
          git status
          changes=$(git status --porcelain | wc -l)
          if [[ $changes -eq 0 ]]; then
            echo "There are no changes to commit. Exiting..."
            exit 0
          fi
          git config user.name "thehub-bot"
          git config user.email "thehub-bot@users.noreply.github.com"

          git checkout -b blog-feed-update
          git add blog-feed.txt
          git commit -m "Update blog-feed.txt (`date`)"
          git push origin --force blog-feed-update

  # create-blog-feed-pr:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 30
  #   needs: blog-feed-to-yaml
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Create PR
  #       uses: peter-evans/create-pull-request@v4
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.THEHUB_BOT_PAT }}
  #       with:
  #         branch: blog-feed-update
  #         title: '[Automated] Update blog-feed.yml'
  #         base: main
  #         body: |
  #           This PR was automatically generated by The Hub Bot. It updates the `blog-feed.yml` file with the latest blog posts.
  #         draft: false
