name: Cancel ongoing action

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

# This allows a subsequently queued workflow run to cancel previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  sleepyTime:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [en, ja, es]
    steps:
      - uses: actions/setup-node@v3.5.1

      - name: Install lolcatjs
        run: npm install --no-save lolcatjs

      - name: Run lolcatjs
        run: ./node_modules/.bin/lolcatjs --help

      - name: Sleep for a long time
        run: |
          echo ${{ matrix.language }}
          sleep 30

      - name: Sleep again
        run: |
          echo ${{ matrix.language }}
          sleep 31

      - name: Sleep one last time
        run: |
          echo ${{ matrix.language }}
          sleep 32
