name: Cancel ongoing action

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

# This allows a subsequently queued workflow run to cancel previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.head_ref }}'
  cancel-in-progress: false

jobs:
  sleepyTime:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [en, ja, es]
    steps:
      - uses: actions/setup-node@v3.8.1

      - name: Install lolcatjs
        run: npm install --no-save lolcatjs

      - name: Run lolcatjs
        run: ./node_modules/.bin/lolcatjs --help

      - name: Randomly fail
        uses: actions/github-script@v7
        with:
          script: |
            if (Math.random() > 0.90) {
              throw new Error("Random error")
            }

      - name: Sleep for a long time
        run: |
          echo ${{ matrix.language }}
          sleep 26

      - name: Sleep again
        run: |
          echo ${{ matrix.language }}
          sleep 27

      - name: Sleep one last time
        run: |
          echo ${{ matrix.language }}
          sleep 28
