name: Party like it's 2022

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read


jobs:
  party:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/setup-node@v2

      - name: Sample output
        run: echo '${{ toJSON(job) }}'

      - name: Sample output 2
        run: echo '${{ toJSON(steps) }}'

      - name: Install lolcatjs
        run: npm install --no-save lolcatjs

      - name: Run lolcatjs
        run: |
          ls -l
          ls -l node_modules
          ls -l node_modules/.bin
          ./node_modules/.bin/lolcatjs --help
