name: Party like it's 2022

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read


jobs:
  party:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/setup-node@v2

      - name: Sample output
        run: echo '${{ toJSON(github) }}'

      - name: Install lolcatjs
        run: npm install --no-save lolcatjs

      - name: Run lolcatjs
        run: lolcatjs --help
