name: Using GitHub script

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

jobs:
  action-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Print something
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo
            console.log(`The owner of ${repo} is ${owner}`)
