name: Post comment on issue

on:
  issues:
    types:
      - labeled

permissions:
  issues: write

jobs:
  post-comment-on-issue:
    if: github.event.label.name == 'help wanted'
    runs-on: ubuntu-latest
    steps:
      - name: Add comment
        env:
          BODY: >
            This issue is available for anyone to work on. **Make sure to reference this issue in
            your pull request.** :sparkles: Thank you for your contribution! :sparkles:
        run: gh issue comment ${{ github.event.issue.number }} --body "$BODY"
